version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk-stretch-node-browsers
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
#      - run:
#          name: Analyze on SonarCloud
#          command: gradle verify sonar:sonar -Dbuild=$CIRCLE_BUILD_NUM
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          - v1-dependencies-
      - run: gradle build -Dbuild=$CIRCLE_BUILD_NUM
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: 
          name: Run JUnit Tests
          command: gradle test -Dbuild=$CIRCLE_BUILD_NUM
#      - store_test_results:
#          path: target
      - run: mvn clean package -Dbuild=$CIRCLE_BUILD_NUM -Dmaven.test.skip=true
      - store_artifacts:
          path: deploy
      - setup_remote_docker
      - run: |
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: 
          name: Building Docker Image
          command: docker build -t devist/devist-chat-api:$CIRCLE_BUILD_NUM .
      - run:
          name: Publish Docker Image
          command: docker push devist/devist-chat-api:$CIRCLE_BUILD_NUM
workflows:
  api_build:
    jobs: 
      - build:
#          context: SonarCloud
          filters:
            branches:
              only:
                - master