version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.1-jdk-stretch-node-browsers
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
#      - run:
#          name: Analyze on SonarCloud
#          command: gradle verify sonar:sonar -Dbuild=$CIRCLE_BUILD_NUM
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle.kts" }}
          - v1-dependencies-
      - run: gradle build -Dbuild=$CIRCLE_BUILD_NUM
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}
      - run: 
          name: Run JUnit Tests
          command: gradle test -Dbuild=$CIRCLE_BUILD_NUM
      - store_test_results:
          path: build/reports
      - store_test_results:
          path: build/test-results
      - run: gradle assemble -Dbuild=$CIRCLE_BUILD_NUM
      - store_artifacts:
          path: build/libs
      - setup_remote_docker
#      - run: |
#          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: Get Docker parameters
          command: |
            version=$(gradle projectVersion | grep "project-version:" |awk '{print $2}')
            group=$(gradle projectGroup | grep "project-group:" |awk '{print $2}')
            name=$(gradle projectName | grep "project-name:" | awk '{print $2}')
      - run:
          name: Building Docker Image
          command: docker build -t $group/$name:$version .
#      - run:
#          name: Publish Docker Image
#          command: docker build -t $group/$name:$version .
workflows:
  api_build:
    jobs: 
      - build:
#          context: SonarCloud
          filters:
            branches:
              only:
                - master